USE projeto1;

LOAD DATA INFILE '/Users/marcioivan/Dropbox/7ºSemestre/MC833/Projetos/projeto1/db/DISCIPLINAS.csv'
IGNORE INTO TABLE DISCIPLINAS
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (CODIGO_DISCIPLINA,TITULO,EMENTA,SALA,HORARIO,COMENTARIO);

LOAD DATA INFILE '/Users/marcioivan/Dropbox/7ºSemestre/MC833/Projetos/projeto1/db/USUARIOS.csv' 
IGNORE INTO TABLE USUARIOS
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (idUSUARIO,LOGIN,SENHA,TIPO);
